# This is a basic workflow to help you get started with Actions
name: Readme Update

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datetime
          pip install feedparser
      
      - name: Update README
        run: python update-post.py
          
      - name: Commit README
        run: |
          git config --global user.email "tmfdl8414@naver.com"
          git config --global user.name "SEULI"
          git add .
          git commit -m "[auto] $(date -u +"%Y-%m-%d") Blog Posting List Update" || exit 0
          git push origin main
